In [4]:
import numpy as np
from numpy.linalg import eig,qr

## Step 1: Define Matrix

In [2]:
matrix = np.array([[2,1,0],[1,3,-1],[0,-1,4]])

## Step 2: Calculate Eigen values and Eignen vectors

In [5]:
eigen_values,eigen_vectors = eig(matrix)
print("Eigen Values:",eigen_values)
print("Eigen Vectors:",eigen_vectors)

Eigen Values: [1.26794919 3.         4.73205081]
Eigen Vectors: [[-0.78867513 -0.57735027 -0.21132487]
 [ 0.57735027 -0.57735027 -0.57735027]
 [ 0.21132487 -0.57735027  0.78867513]]


# Step 3: Verify Eigen vectors that correspond to a distinct eigen values are indepednent

### Step 3.1: Check Eigen values are Distinct

In [15]:
if len(eigen_values) == len(np.unique(eigen_values)):
    print("Eigen Vectors are distinct")
else:
    print("Eigen vectors are not distinct")


Eigen Vectors are distinct


### Step 3.2: Check Linear Independance

#### Step 3.2.1: Make a Matrix by combining the eigen vectors

In [7]:
eig_matrix = np.column_stack(eigen_vectors)

#### Step 3.2.2: Find the QR decomposition

In [9]:
rref,pivot_columns = qr(eig_matrix)

In [16]:
print(rref)
print(pivot_columns)

[[-0.78867513  0.57735027  0.21132487]
 [-0.57735027 -0.57735027 -0.57735027]
 [-0.21132487 -0.57735027  0.78867513]]
[[ 1.00000000e+00 -1.11022302e-16 -5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00  3.33066907e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


#### Step 3.2.4: Check independance 

In [14]:
if len(pivot_columns) == len(eigen_values):
    print("Eigen Vectors are Linearly Independent")
else:
    print("Eigen vectors are Linearly Dependent")


Eigen Vectors are Linearly Independent
