In [28]:
import numpy as np

## Step 1: Define the matrix

In [29]:
A = np.array([[0,1,2],[1,0,3],[4,-3,8]])
print(A)

[[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]


## Step 2: Calculate Inverse of the matrix

### Step 2.1: Augment A with identity matrix

In [30]:
augmentedmatrix = np.hstack((A, np.identity(len(A)))) #Takes only one argument. 
print(augmentedmatrix)

[[ 0.  1.  2.  1.  0.  0.]
 [ 1.  0.  3.  0.  1.  0.]
 [ 4. -3.  8.  0.  0.  1.]]


### Step 2.2: Perform Gaussian elimination to convert the augmented matrix to reduced row echelon form

In [31]:
n = len(augmented_matrix)# Return number of rows
n

3

In [32]:
for i in range(n): # For each row in the augmented matrix
    # Partial pivoting
    max_row = i #Indicates the current row here , it may be 0,1,2 row
    for k in range(i+1, n): # Indicates the rows after the current row , for example if current row is 0 then k value will be 1,2
        if abs(augmented_matrix[k][i]) > abs(augmented_matrix[max_row][i]): #find the pivot element (which is the largest element)
            max_row = k
    augmented_matrix[[i, max_row]] = augmented_matrix[[max_row, i]] #Swapping

    # Make the diagonal element 1
    divisor = augmented_matrix[i][i]#fetching the diagonals like matrix[1,1],matrix[2,2],matrix[3,3]
    augmented_matrix[i] /= divisor #Divede the entire current row with the diagonal value

    # Make other elements in the current column zero
    for k in range(n):
        if k != i: #Rows other than the current one
            factor = augmented_matrix[k][i] #Extracting the element which you want to make it as zero
            augmented_matrix[k] -= factor * augmented_matrix[i] # Perfoming the opertion on the entire row

### Step 2.3: Extract the inverse matrix from the augmented matrix

In [33]:
inverse_matrix = augmented_matrix[:, n:]

# Print the inverse matrix
print("Inverse of A:")
print(inverse_matrix)

Inverse of A:
[[ 1.4 -0.8 -1. ]
 [-0.2  0.4  0. ]
 [-1.6  0.2  2. ]]


In [25]:
#Cross Verifying with the output of python built-in function
inverse_A = np.linalg.inv(A)
print(inverse_A)

[[ 1.4 -0.8 -1. ]
 [-0.2  0.4  0. ]
 [-1.6  0.2  2. ]]
